insert into paises (nombre, Regiones_nombre) values ('VDxvmL', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('Io6mtT', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('IvRvyI', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('KmmlcP', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('YuIzjI', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('1GrvtK', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('K1OlwZ', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('CealbL', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('WQlgmA', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('OO6nzB', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('M06bdX', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('ZW9vjF', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('10EkjG', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('9ASyuG', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('JRVklP', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('YkwkxJ', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('0KabiN', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('YllvqQ', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('XcidcR', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('9hGcfA', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('MNszuU', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('OJPffC', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('F7IybC', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('KfdtnX', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('4RFhhH', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('9jPumV', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('BqysjL', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('QPseiI', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('AVketI', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('DdhpaC', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('KiTudZ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('5VNjdS', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('3oOkhP', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('RcbhrO', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('W8vlsW', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('0f1ouE', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('UnhpxV', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('1LqvdH', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('EbvslS', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('J8grrU', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('DJ6stZ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('W9KymW', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('JP8dlL', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('0WevkL', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('1GEbvL', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('5VlftV', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('UgBwfF', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('3jdluI', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('UlsgnN', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('T4TquI', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('UsPblJ', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('SrhynY', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('PJXjyX', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('2i6jlL', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('NfhfxU', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('H5ekwO', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('0OQebC', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('WakfwQ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('AAwzsA', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('4YovuD', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('MgRfhA', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('75KlyA', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('TbopaI', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('21ejfG', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('USoctJ', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('4DpqgG', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('XvoabJ', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('7AGfpO', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('Zc6pdS', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('MLVczO', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('NxSueL', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('OAyjbT', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('9oxoxP', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('Tw4lmB', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('RQhvfK', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('7T0apH', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('UnibsW', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('Zh2jwZ', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('NjdhbX', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('No8vsO', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('9RawjR', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('UVUwlG', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('0nNsqU', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('1N4vgD', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('EISwfO', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('KusakD', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('6dgdkP', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('ZhexnX', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('O33gsM', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('SIWuwB', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('LzjfvW', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('1eKgvZ', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('ZiEooJ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('IN7irX', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('AC3jxB', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('0hFfbM', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('HQQlgN', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('FiWwmA', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('7fJjkD', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('OyhinA', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('XvjvfX', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('9rAbdM', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('VmQazS', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('YahwmR', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('UFYvjF', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('HicbiV', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('43fjvI', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('DFFriX', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('13rntI', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('21WhoP', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('9VOcjK', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('RvValH', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('E9swyU', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('WQfpsK', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('DXmncQ', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('6OEapH', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('OsUbgF', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('YWipgC', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('BJ2sjZ', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('1KWqyX', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('PKWrrB', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('P9wetA', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('UJzpaA', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('GVyghV', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('GAZjuV', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('Ci9fiW', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('OOPlmF', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('3nJpcS', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('JeDhkY', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('Ai9xgJ', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('3wpaoC', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('UWZfqO', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('X3njbC', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('6M3aqA', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('AeMhsX', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('CeGhvC', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('IJfrlR', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('UiuioZ', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('VgossJ', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('QKidkP', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('9T7fmW', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('KunucD', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('GLRzuE', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('EEzbcE', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('0zKljT', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('FuQuqD', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('EDWpiE', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('6jWovL', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('PRDhpX', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('LKBwaX', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('345nwX', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('HRLuyS', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('3rCqaC', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('E9ZsuA', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('6PqfnC', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('VxmmhT', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('CoxbiA', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('PkVkaX', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('JOichN', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('7F7xfC', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('PbciyT', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('756euF', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('O0WywO', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('A86vmB', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('XMjbkT', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('7tAxqQ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('SemfyW', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('Ud1kpV', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('92UxmG', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('1xJagN', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('2iDdkZ', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('DPMltI', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('HTwxcU', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('RJNsfA', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('ZqsfdW', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('42oenF', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('HEjlgF', 'Asia');
insert into paises (nombre, Regiones_nombre) values ('BAfidQ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('1B6cpS', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('1IubbX', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('JAevdC', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('LrUsaK', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('MdcibM', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('OwplkY', 'Norte America');
insert into paises (nombre, Regiones_nombre) values ('1WldrZ', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('TY6oyB', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('XGvjcL', 'Oceania');
insert into paises (nombre, Regiones_nombre) values ('SMJanZ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('AEWkfZ', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('IFqxxZ', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('TmlgdQ', 'Europa');
insert into paises (nombre, Regiones_nombre) values ('IEGlgO', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('Eh1dyH', 'Sur America');
insert into paises (nombre, Regiones_nombre) values ('5bUbuI', 'Africa');
insert into paises (nombre, Regiones_nombre) values ('MqEuhP', 'Asia');
